# Generated by Django 5.0.1 on 2025-04-26 20:00

from django.db import migrations, models


def fix_address_and_checkout(apps, schema_editor):
    """
    Fix the Address model by adding the phone field
    and update Checkout to link to the correct Address
    """
    # Create the Address model directly in the database
    db_alias = schema_editor.connection.alias
    Address = apps.get_model("orders", "Address")

    # Create Address objects based on the current ShippingAddress
    ShippingAddress = apps.get_model("orders", "ShippingAddress")
    Checkout = apps.get_model("orders", "Checkout")

    # First, get or create an Address for each ShippingAddress
    for shipping_address in ShippingAddress.objects.using(db_alias).all():
        # Create a corresponding Address
        address, created = Address.objects.using(db_alias).get_or_create(
            user=shipping_address.user,
            address_type="shipping",
            full_name=shipping_address.full_name,
            street_address=shipping_address.street_address,
            city=shipping_address.city,
            state=shipping_address.state,
            postal_code=shipping_address.postal_code,
            country=shipping_address.country,
            defaults={
                "apartment_address": shipping_address.apartment_unit,
                "is_default": shipping_address.is_default,
                "phone": shipping_address.phone,
                "created_at": shipping_address.created_at,
                "updated_at": shipping_address.updated_at,
            },
        )

        # Update all Checkout objects that reference this shipping address
        Checkout.objects.using(db_alias).filter(
            shipping_address_id=shipping_address.id
        ).update(shipping_address=address)


def reverse_func(apps, schema_editor):
    """
    No need to reverse this operation
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_address_options_and_more"),
    ]

    operations = [
        # First add the phone field to Address if it doesn't already exist
        migrations.AddField(
            model_name="address",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Ensure Checkout references Address, not ShippingAddress
        migrations.AlterField(
            model_name="checkout",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="checkout_shipping_orders",
                to="orders.address",
            ),
        ),
        # Run the data migration
        migrations.RunPython(fix_address_and_checkout, reverse_func),
    ]
