# Generated by Django 5.0.1 on 2025-04-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_merge_20250426_1507"),
    ]

    operations = []
