# Generated by Django 5.0.1 on 2025-06-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_rename_apartment_address_to_apartment_unit"),
        ("orders", "0010_fix_migration_errors"),
    ]

    operations = []
