# Generated by Django 5.0.1 on 2025-04-26 15:01

import django.db.models.deletion
from django.db import migrations, models


def migrate_shipping_addresses_before_field_change(apps, schema_editor):
    """
    Temporarily set shipping_address to NULL for all Checkout instances
    before the schema changes to avoid integrity errors
    """
    Checkout = apps.get_model("orders", "Checkout")
    Checkout.objects.all().update(shipping_address=None)


def reverse_migration(apps, schema_editor):
    """No need to reverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_address_options_and_more"),
    ]

    operations = [
        # Add the RunPython operation before schema changes
        migrations.RunPython(
            migrate_shipping_addresses_before_field_change, reverse_migration
        ),
        # First modify the shipping_address field to allow NULL values temporarily
        migrations.AlterField(
            model_name="checkout",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkout_shipping_orders",
                to="orders.shippingaddress",
                null=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.RemoveField(
            model_name="address",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="address",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkout_shipping_orders",
                to="orders.address",
                null=True,  # Keep it nullable for data migration in the next step
            ),
        ),
    ]
