# Generated by Django 5.0.1 on 2025-04-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_migrate_shipping_addresses_to_address"),
        ("orders", "0005_fix_phone_field"),
    ]

    operations = []
