# Generated by Django 5.0.1 on 2025-06-08 00:18

import django.db.models.deletion
from django.db import migrations, models


def fix_apartment_field_conditionally(apps, schema_editor):
    """
    Handle apartment_address to apartment_unit transition safely
    """
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        # Check if the table exists and get its schema
        cursor.execute("PRAGMA table_info(orders_address);")
        columns = cursor.fetchall()
        column_names = [col[1] for col in columns]

        has_apartment_address = "apartment_address" in column_names
        has_apartment_unit = "apartment_unit" in column_names

        if has_apartment_address and not has_apartment_unit:
            # Simple rename case
            cursor.execute("PRAGMA foreign_keys=off;")
            cursor.execute(
                """
                ALTER TABLE orders_address 
                RENAME COLUMN apartment_address TO apartment_unit;
            """
            )
            cursor.execute("PRAGMA foreign_keys=on;")
        elif not has_apartment_address and not has_apartment_unit:
            # Need to add apartment_unit
            cursor.execute(
                """
                ALTER TABLE orders_address 
                ADD COLUMN apartment_unit VARCHAR(255) NULL;
            """
            )
        elif has_apartment_address and has_apartment_unit:
            # Both exist - merge the data and drop apartment_address
            cursor.execute("PRAGMA foreign_keys=off;")
            # Update apartment_unit with data from apartment_address where apartment_unit is null/empty
            cursor.execute(
                """
                UPDATE orders_address 
                SET apartment_unit = apartment_address 
                WHERE apartment_unit IS NULL OR apartment_unit = '';
            """
            )
            # Drop the apartment_address column by recreating the table
            cursor.execute(
                """
                CREATE TABLE _orders_address_temp AS 
                SELECT id, address_type, full_name, street_address, apartment_unit,
                       city, state, postal_code, country, phone, is_default, 
                       created_at, updated_at, user_id
                FROM orders_address;
            """
            )
            cursor.execute("DROP TABLE orders_address;")
            cursor.execute("ALTER TABLE _orders_address_temp RENAME TO orders_address;")
            cursor.execute(
                "CREATE INDEX orders_address_user_id ON orders_address (user_id);"
            )
            cursor.execute("PRAGMA foreign_keys=on;")
        # If only apartment_unit exists, nothing to do


def reverse_func(apps, schema_editor):
    """No need to reverse"""
    pass


class Migration(migrations.Migration):

    replaces = [
        ("orders", "0007_fix_migration_issue"),
        ("orders", "0010_fix_migration_errors"),
        ("orders", "0008_remove_deprecated_models"),
        ("orders", "0009_rename_apartment_address_to_apartment_unit"),
        ("orders", "0011_merge_20250608_0017"),
    ]

    dependencies = [
        ("orders", "0006_merge_20250426_1507"),
    ]

    operations = [
        # Handle apartment field transition
        migrations.RunPython(fix_apartment_field_conditionally, reverse_func),
        # Add checkout field to OrderStatusHistory
        migrations.AddField(
            model_name="orderstatushistory",
            name="checkout",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="orders.checkout",
            ),
        ),
        # Remove deprecated models
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
