# Generated by Django 5.0.1 on 2025-06-08 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("orders", "0007_fix_migration_issue"),
        ("orders", "0010_fix_migration_errors"),
        ("orders", "0008_remove_deprecated_models"),
        ("orders", "0009_rename_apartment_address_to_apartment_unit"),
        ("orders", "0011_merge_20250608_0017"),
    ]

    dependencies = [
        ("orders", "0006_merge_20250426_1507"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="apartment_unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="checkout",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="orders.checkout",
            ),
        ),
        migrations.RenameField(
            model_name="orderstatushistory",
            old_name="order",
            new_name="checkout",
        ),
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="apartment_address",
            new_name="apartment_unit",
        ),
    ]
