# Generated by Django 5.0.4 on 2025-06-08 00:21
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_merge_20250608_0017"),
    ]

    operations = [
        migrations.RunSQL(
            # Check if phone column exists in address table and remove it if it does
            """
            PRAGMA foreign_keys=off;
            
            -- Create a temp table without the duplicate column
            CREATE TABLE orders_address_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                street_address VARCHAR(255) NOT NULL,
                apartment_unit VARCHAR(255) NULL,
                city VARCHAR(255) NOT NULL,
                state VARCHAR(255) NOT NULL,
                country VARCHAR(255) NOT NULL,
                postal_code VARCHAR(255) NOT NULL,
                phone VARCHAR(255) NULL,
                is_default BOOL NOT NULL,
                user_id INTEGER NOT NULL REFERENCES auth_user (id)
            );
            
            -- Copy data from old table to new table
            INSERT INTO orders_address_new 
            SELECT id, street_address, apartment_unit, city, state, country, postal_code, phone, is_default, user_id 
            FROM orders_address;
            
            -- Drop old table
            DROP TABLE orders_address;
            
            -- Rename new table to old table name
            ALTER TABLE orders_address_new RENAME TO orders_address;
            
            -- Recreate indices
            CREATE INDEX orders_address_user_id ON orders_address (user_id);
            
            PRAGMA foreign_keys=on;
            """,
            # Reverse SQL - we don't need to do anything in reverse since this is a fix
            "SELECT 1;",
        ),
    ]
