# Generated by Django 5.0.4 on 2025-06-08 00:22
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_fix_duplicate_phone_column"),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Make sure OrderStatusHistory uses Checkout model correctly
            """
            -- First, check if we need to clean up OrderStatusHistory table
            PRAGMA foreign_keys=off;
            
            -- Create a new OrderStatusHistory table with correct relationships
            CREATE TABLE orders_orderstatushistory_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                status VARCHAR(20) NOT NULL,
                notes TEXT NULL,
                created_at DATETIME NOT NULL,
                created_by_id INTEGER NULL REFERENCES auth_user (id),
                checkout_id INTEGER NOT NULL REFERENCES orders_checkout (id)
            );
            
            -- Copy data, ensuring we link to checkout
            INSERT INTO orders_orderstatushistory_new (id, status, notes, created_at, created_by_id, checkout_id)
            SELECT id, status, notes, created_at, created_by_id, 
                   COALESCE(checkout_id, id) -- Fall back to ID if checkout_id is NULL
            FROM orders_orderstatushistory;
            
            -- Drop old table
            DROP TABLE orders_orderstatushistory;
            
            -- Rename new table
            ALTER TABLE orders_orderstatushistory_new RENAME TO orders_orderstatushistory;
            
            -- Recreate indices
            CREATE INDEX orders_orderstatushistory_created_by_id ON orders_orderstatushistory (created_by_id);
            CREATE INDEX orders_orderstatushistory_checkout_id ON orders_orderstatushistory (checkout_id);
            
            PRAGMA foreign_keys=on;
            """,
            # Reverse SQL - We don't need to reverse this, it's a fix
            "SELECT 1;",
        ),
    ]
