# Generated by Django 5.0.1 on 2025-06-08 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_fix_migration_graph"),
        ("orders", "0014_complete_database_cleanup"),
    ]

    operations = []
