# Generated by Django 5.0.4 on 2025-06-08 08:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_fix_orderstatushistory_migration"),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Safe schema manipulation that checks if columns exist first
            """
            PRAGMA foreign_keys=off;
            
            -- Create a temp table structure to check existing columns
            CREATE TEMPORARY TABLE _column_check AS
            SELECT name FROM pragma_table_info('orders_address');
            
            -- Drop and recreate the table only if there's a duplicate phone column
            SELECT CASE 
                WHEN (SELECT COUNT(*) FROM _column_check WHERE name = 'phone') > 1 
                THEN (
                    -- Create a new table with correct schema
                    CREATE TABLE orders_address_new (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        address_type VARCHAR(10) NOT NULL,
                        full_name VARCHAR(255) NOT NULL,
                        street_address VARCHAR(255) NOT NULL,
                        apartment_unit VARCHAR(255) NULL,
                        city VARCHAR(100) NOT NULL,
                        state VARCHAR(100) NOT NULL,
                        postal_code VARCHAR(20) NOT NULL,
                        country VARCHAR(100) NOT NULL,
                        phone VARCHAR(50) NULL,
                        is_default BOOL NOT NULL,
                        created_at DATETIME NOT NULL,
                        updated_at DATETIME NOT NULL,
                        user_id INTEGER NOT NULL REFERENCES auth_user (id)
                    );
                    
                    -- Copy data with only one phone column
                    INSERT INTO orders_address_new 
                    SELECT id, address_type, full_name, street_address, apartment_unit, 
                           city, state, postal_code, country, phone, 
                           is_default, created_at, updated_at, user_id 
                    FROM orders_address;
                    
                    -- Drop old table
                    DROP TABLE orders_address;
                    
                    -- Rename new table
                    ALTER TABLE orders_address_new RENAME TO orders_address;
                    
                    -- Recreate indices
                    CREATE INDEX orders_address_user_id ON orders_address (user_id);
                )
                ELSE (
                    -- Nothing to do if there's only one phone column
                    SELECT 1
                )
            END;
            
            -- Clean up
            DROP TABLE _column_check;
            
            PRAGMA foreign_keys=on;
            """,
            # Reverse SQL - No need to reverse a schema fix
            "SELECT 1;",
        ),
    ]
